# The Basics of NumPy Arrays

### <u>Basic array manipulation</u>

In [5]:
import numpy as np

np.random.seed(0)  # seed for reproducibility

x3 = np.random.randint(3, 10, size=(2, 3, 4))
print(x3)

[[[7 8 3 6]
  [6 6 4 6]
  [8 5 7 9]]

 [[3 3 7 5]
  [4 9 9 3]
  [4 8 4 8]]]


In [9]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)
print('')
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")  # itemsize x size

x3 ndim: 3
x3 shape: (2, 3, 4)
x3 size: 24

dtype: int64
itemsize: 8 bytes
nbytes: 192 bytes


## Array Slicing
#### x[start:stop:step]
For negative values of steps, the defaults for start, stop change

In [10]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [12]:
x[5::-2]

array([5, 3, 1])

In [16]:
x1 = np.array([range(i, i+4) for i in [1, 5, 9]])
x1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
x1[:2, :3]

array([[1, 2, 3],
       [5, 6, 7]])

In [20]:
x1[1, :]

array([5, 6, 7, 8])

In [21]:
x1[:, 1]

array([ 2,  6, 10])

## Subarrays as no-copy views
One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
<b> Genuine copies can be made by copy() method.

In [24]:
x1_sub = x1[:2, :2]
print(x1_sub)

[[1 2]
 [5 6]]


Changing the view changes the original array

In [28]:
x1_sub[0, 0] = 99
print(x1)
x1_sub[0, 0] = 1

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Reshaping of arrays

In [29]:
grid = np.arange(1, 10).reshape((3, 3))  # works when the size is same
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Creating row/column vector
reshape() method and newaxis keyword

In [32]:
x = np.array([1, 2, 3])

x.reshape((1, 3))

array([[1, 2, 3]])

In [33]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [36]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [37]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Concatenation

<b>NOTE:</b> We can also use vstack, hstack and dstack for axes=0, 1, 2 respectively.

In [41]:
y = np.arange(1, 4)[::-1]
z = np.array([0, 0, 0])
np.concatenate([x, y, z])

array([1, 2, 3, 3, 2, 1, 0, 0, 0])

In [45]:
grid = np.random.randint(0, 10, size=(2, 3, 4))
print(grid)

[[[8 9 4 3]
  [0 3 5 0]
  [2 3 8 1]]

 [[3 3 3 7]
  [0 1 9 9]
  [0 4 7 3]]]


In [46]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[[8, 9, 4, 3],
        [0, 3, 5, 0],
        [2, 3, 8, 1]],

       [[3, 3, 3, 7],
        [0, 1, 9, 9],
        [0, 4, 7, 3]],

       [[8, 9, 4, 3],
        [0, 3, 5, 0],
        [2, 3, 8, 1]],

       [[3, 3, 3, 7],
        [0, 1, 9, 9],
        [0, 4, 7, 3]]])

In [47]:
np.concatenate([grid, grid], axis=1)

array([[[8, 9, 4, 3],
        [0, 3, 5, 0],
        [2, 3, 8, 1],
        [8, 9, 4, 3],
        [0, 3, 5, 0],
        [2, 3, 8, 1]],

       [[3, 3, 3, 7],
        [0, 1, 9, 9],
        [0, 4, 7, 3],
        [3, 3, 3, 7],
        [0, 1, 9, 9],
        [0, 4, 7, 3]]])

In [48]:
np.concatenate([grid, grid], axis=2)

array([[[8, 9, 4, 3, 8, 9, 4, 3],
        [0, 3, 5, 0, 0, 3, 5, 0],
        [2, 3, 8, 1, 2, 3, 8, 1]],

       [[3, 3, 3, 7, 3, 3, 3, 7],
        [0, 1, 9, 9, 0, 1, 9, 9],
        [0, 4, 7, 3, 0, 4, 7, 3]]])

## Splitting of arrays


In [52]:
a, b = np.split(grid, [1])
print(a)
print(b)

[[[8 9 4 3]
  [0 3 5 0]
  [2 3 8 1]]]
[[[3 3 3 7]
  [0 1 9 9]
  [0 4 7 3]]]


In [53]:
a, b = np.vsplit(grid, [1])
print(a)
print(b)

[[[8 9 4 3]
  [0 3 5 0]
  [2 3 8 1]]]
[[[3 3 3 7]
  [0 1 9 9]
  [0 4 7 3]]]


In [54]:
a, b = np.hsplit(grid, [2])
print(a)
print(b)

[[[8 9 4 3]
  [0 3 5 0]]

 [[3 3 3 7]
  [0 1 9 9]]]
[[[2 3 8 1]]

 [[0 4 7 3]]]


In [56]:
a, b = np.dsplit(grid, [2])
print(a)
print(b)

[[[8 9]
  [0 3]
  [2 3]]

 [[3 3]
  [0 1]
  [0 4]]]
[[[4 3]
  [5 0]
  [8 1]]

 [[3 7]
  [9 9]
  [7 3]]]
