# Boolean Operators


In [2]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [3]:
x < 3

array([ True,  True, False, False, False])

In [4]:
x > 4

array([False, False, False, False,  True])

In [5]:
(2 * x) == (x ** 2) 

array([False,  True, False, False, False])

In [15]:
x = np.random.randint(10, size=(3, 2, 2))
x

array([[[5, 1],
        [8, 9]],

       [[7, 2],
        [8, 1]],

       [[3, 4],
        [9, 6]]])

In [16]:
x < 5


array([[[False,  True],
        [False, False]],

       [[False,  True],
        [False,  True]],

       [[ True,  True],
        [False, False]]])

In [19]:
np.sum(x < 5)   # number of elements less than 5

5

In [20]:
np.sum(x < 5, axis=0)

array([[1, 3],
       [0, 1]])

In [21]:
np.all(x < 10)

True

In [22]:
np.any(x > 10)

False

In [31]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 4, 8])
np.any(a>b)

False

Bitwise operators &, |, ^, ~ work as per their usual definition

## Boolean Arrays as Masks

A powerful pattern is to use Boolean arrays as masks, to select particular subsets of the data themselves. Returning to our x array from before, suppose we want an array of all values in the array that are less than, say, 5

In [23]:
x = np.random.randint(10, size=(3, 4))
x

array([[7, 2, 3, 9],
       [7, 8, 2, 9],
       [6, 9, 7, 4]])

In [24]:
x[x<5]

array([2, 3, 2, 4])

Here x<5 acts as mask, and [] operator returns 1D array satisfying the mask.
<br>We can combine masks by bitwise operators to return required values.


In [26]:
bin(42 | 59)

'0b111011'

In [28]:
bool(42 and 59)

True