# Numpy Arrays

## <u>Common methods to generate numpy arrays</u>

In [2]:
import numpy as np
import array

In [4]:
# Multi-dimensional array
np.array([range(i, i+3) for i in [1, 2, 3]])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [5]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((3, 5), float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((2, 2), 5.6)

array([[5.6, 5.6],
       [5.6, 5.6]])

In [8]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.linspace(0, 2, 9) # 9 evenly spaced integers between 0 and 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
np.random.random((2, 3))  # 2X3 matrix with random numbers between 0 & 1

array([[0.81299225, 0.0777262 , 0.48305786],
       [0.12069286, 0.18311432, 0.35696537]])

In [14]:
# random numbers with average 4 and standard deviation 1
np.random.normal(4, 1, (3, 3))

array([[4.6073914 , 4.11827453, 4.19624863],
       [4.82693351, 5.21774371, 4.40374822],
       [4.49569773, 2.3303243 , 5.36485501]])

In [15]:
# random int in [0, 8)
np.random.randint(0, 8, (3, 3))

array([[3, 7, 2],
       [6, 2, 0],
       [1, 7, 2]])

In [18]:
# Create a 2x2 identity matrix
np.eye(2, dtype='int')

array([[1, 0],
       [0, 1]])

In [19]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([4.64847884e-310, 2.12199579e-314, 0.00000000e+000])