# Structured Data

In [3]:
import numpy as np

name = ['a', 'b', 'c']
age = [10, 45, 32]
weight = [55.4, 67.3, 43.0]

data = np.zeros(3, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [4]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('a', 10, 55.4) ('b', 45, 67.3) ('c', 32, 43. )]


In [5]:
data[-1]['name']

'c'

In [7]:
# Get names where age is under 30
data[data['age'] < 30]['name']

array(['a'], dtype='<U10')

### Structures array with a numpy matrix as a component

In [8]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
