In [9]:
from __future__ import print_function
import torch
size = int(2)
x = torch.rand(size, size)
y = torch.rand(size, size)
z = x*y
print(x)
print(y)
print(z)

tensor([[2.3580e-04, 2.4624e-01],
        [3.5883e-01, 8.1670e-01]])
tensor([[0.1205, 0.2418],
        [0.6811, 0.1740]])
tensor([[2.8408e-05, 5.9552e-02],
        [2.4438e-01, 1.4212e-01]])


In [10]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[1.0002, 1.2462],
        [1.3588, 1.8167]], device='cuda:0')
tensor([[1.0002, 1.2462],
        [1.3588, 1.8167]], dtype=torch.float64)


In [11]:
!nvidia-smi

Tue May 12 17:57:19 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1650    On   | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0    13W /  N/A |   1249MiB /  3911MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [12]:
!nvidia-smi

Tue May 12 17:57:57 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1650    On   | 00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8     3W /  N/A |   1249MiB /  3911MiB |      7%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  